name: CI Workflow

on:
  release:
    types: [created]

jobs:
  #builds and deploys libs to github packages
  build-and-deploy-libs:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@main
    with:
      java-version: 21
      sbom-path: integrasjonspunkt/target
      fetch-depth: 0
      application-path: integrasjonspunkt/
    secrets: inherit

  build-and-deploy-image:
    #builds and deploys docker image to Github Packages Container Registry
    needs: build-and-deploy-libs
    uses: felleslosninger/github-workflows/.github/workflows/ci-docker-build-publish-integrasjonspunkt.yml@main
    with:
      slack-channel-id: C05NLQCFR41
    secrets: inherit
