name: CI Workflow

on:
  release:
    types: [created]

jobs:
  #builds and deploys libs to github packages
  call-workflow-maven-install-deploy:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@main
    with:
      package-version: ${{ github.event.release.tag_name }}
      deployment-repository: ${{ github.repository }}
      java-version: 8
      sbom-path: ./
      application-path: integrasjonspunkt/
    secrets: inherit

  build-and-deploy-image:
    #builds and deploys docker image to Github Packages Container Registry
    needs: call-workflow-maven-install-deploy
    uses: felleslosninger/github-workflows/.github/workflows/ci-docker-build-publish-integrasjonspunkt.yml@main
    with:
      package-version: ${{ github.event.release.tag_name }}
      slack-channel-id: C05NLQCFR41
    secrets: inherit
